// <auto-generated />
using System;
using BookStore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookStore.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240713050520_seeds")]
    partial class seeds
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.32");

            modelBuilder.Entity("AuthorBook", b =>
                {
                    b.Property<int>("AuthorsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BooksId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AuthorsId", "BooksId");

                    b.HasIndex("BooksId");

                    b.ToTable("AuthorBook");
                });

            modelBuilder.Entity("BookStore.Data.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Author");

                    b.HasData(
                        new
                        {
                            Id = 1005,
                            Age = 56,
                            Name = "Ashtyn Conroy"
                        },
                        new
                        {
                            Id = 1006,
                            Age = 37,
                            Name = "Jana Collier"
                        },
                        new
                        {
                            Id = 1007,
                            Age = 36,
                            Name = "Prof. Danyka Kuvalis"
                        },
                        new
                        {
                            Id = 1008,
                            Age = 61,
                            Name = "Maxime Crooks"
                        },
                        new
                        {
                            Id = 1009,
                            Age = 59,
                            Name = "Emery Wolff"
                        },
                        new
                        {
                            Id = 1010,
                            Age = 36,
                            Name = "Leola Spinka"
                        },
                        new
                        {
                            Id = 1011,
                            Age = 43,
                            Name = "Adele Barrows"
                        },
                        new
                        {
                            Id = 1012,
                            Age = 35,
                            Name = "Mr. Mekhi Will III"
                        },
                        new
                        {
                            Id = 1013,
                            Age = 27,
                            Name = "Jace Hartmann II"
                        },
                        new
                        {
                            Id = 1014,
                            Age = 49,
                            Name = "Harley O'Hara"
                        },
                        new
                        {
                            Id = 1015,
                            Age = 45,
                            Name = "Marvin Luettgen"
                        },
                        new
                        {
                            Id = 1016,
                            Age = 61,
                            Name = "Mrs. Mollie Upton I"
                        },
                        new
                        {
                            Id = 1017,
                            Age = 43,
                            Name = "Ms. Stella Sammy Bergnaum"
                        },
                        new
                        {
                            Id = 1018,
                            Age = 21,
                            Name = "Miss Travon Alex D'Amore Sr."
                        },
                        new
                        {
                            Id = 1019,
                            Age = 41,
                            Name = "Ms. Carolyn Huel"
                        },
                        new
                        {
                            Id = 1020,
                            Age = 40,
                            Name = "Ms. Anabel Tavares Gusikowski V"
                        },
                        new
                        {
                            Id = 1021,
                            Age = 26,
                            Name = "Miss Keara Ziemann Jr."
                        },
                        new
                        {
                            Id = 1022,
                            Age = 43,
                            Name = "Ms. Josiah Freeda Durgan"
                        },
                        new
                        {
                            Id = 1023,
                            Age = 59,
                            Name = "Rebeca Koelpin"
                        },
                        new
                        {
                            Id = 1024,
                            Age = 48,
                            Name = "Jeffery Justina Turner DVM"
                        },
                        new
                        {
                            Id = 1025,
                            Age = 33,
                            Name = "Yadira Abshire"
                        },
                        new
                        {
                            Id = 1026,
                            Age = 46,
                            Name = "Prof. Mitchell Jessy Gibson"
                        },
                        new
                        {
                            Id = 1027,
                            Age = 35,
                            Name = "Marcus Hilpert DVM"
                        },
                        new
                        {
                            Id = 1028,
                            Age = 53,
                            Name = "Nestor Crona"
                        },
                        new
                        {
                            Id = 1029,
                            Age = 52,
                            Name = "Dr. Elizabeth Aurore Bartell PhD"
                        },
                        new
                        {
                            Id = 1030,
                            Age = 29,
                            Name = "Dr. Corine Shanon Cummerata"
                        },
                        new
                        {
                            Id = 1031,
                            Age = 38,
                            Name = "Clara Keeling"
                        },
                        new
                        {
                            Id = 1032,
                            Age = 31,
                            Name = "Bernard Padberg"
                        },
                        new
                        {
                            Id = 1033,
                            Age = 41,
                            Name = "Eldridge Adams"
                        },
                        new
                        {
                            Id = 1034,
                            Age = 49,
                            Name = "Floyd Leannon"
                        },
                        new
                        {
                            Id = 1035,
                            Age = 43,
                            Name = "Mrs. Mohamed Deion Brekke"
                        },
                        new
                        {
                            Id = 1036,
                            Age = 54,
                            Name = "Mr. Zion Devan Murphy"
                        },
                        new
                        {
                            Id = 1037,
                            Age = 31,
                            Name = "Fred Daugherty"
                        },
                        new
                        {
                            Id = 1038,
                            Age = 62,
                            Name = "Wendell Kuphal"
                        },
                        new
                        {
                            Id = 1039,
                            Age = 26,
                            Name = "Victoria Lesch"
                        },
                        new
                        {
                            Id = 1040,
                            Age = 31,
                            Name = "Ms. Zackary Ullrich Jr."
                        },
                        new
                        {
                            Id = 1041,
                            Age = 60,
                            Name = "Ms. Sincere Hilpert"
                        },
                        new
                        {
                            Id = 1042,
                            Age = 38,
                            Name = "Rodrigo Lueilwitz"
                        },
                        new
                        {
                            Id = 1043,
                            Age = 23,
                            Name = "Ressie Becker"
                        },
                        new
                        {
                            Id = 1044,
                            Age = 47,
                            Name = "Lyla Daugherty"
                        },
                        new
                        {
                            Id = 1045,
                            Age = 25,
                            Name = "Ms. Keith Emanuel Greenholt"
                        },
                        new
                        {
                            Id = 1046,
                            Age = 28,
                            Name = "Tamara Quitzon"
                        },
                        new
                        {
                            Id = 1047,
                            Age = 46,
                            Name = "Cassandre Kub"
                        },
                        new
                        {
                            Id = 1048,
                            Age = 41,
                            Name = "Arnold Lemke"
                        },
                        new
                        {
                            Id = 1049,
                            Age = 56,
                            Name = "Dr. Stephania Allene Gaylord PhD"
                        },
                        new
                        {
                            Id = 1050,
                            Age = 39,
                            Name = "Zakary Quitzon"
                        },
                        new
                        {
                            Id = 1051,
                            Age = 55,
                            Name = "Mrs. Bethel Fermin Keeling MD"
                        },
                        new
                        {
                            Id = 1052,
                            Age = 29,
                            Name = "Simone West"
                        },
                        new
                        {
                            Id = 1053,
                            Age = 24,
                            Name = "Paxton Hand"
                        },
                        new
                        {
                            Id = 1054,
                            Age = 54,
                            Name = "Agustin Breitenberg"
                        });
                });

            modelBuilder.Entity("BookStore.Data.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Pages")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PubDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("PublisherId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StoreId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StoreId");

                    b.ToTable("Book");
                });

            modelBuilder.Entity("BookStore.Data.Models.Publisher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Publisher");

                    b.HasData(
                        new
                        {
                            Id = 105,
                            Name = "Maryam Spencer"
                        },
                        new
                        {
                            Id = 106,
                            Name = "Mrs. Marcelino Evangeline Rempel"
                        },
                        new
                        {
                            Id = 107,
                            Name = "Elliott Zemlak"
                        },
                        new
                        {
                            Id = 108,
                            Name = "Jess Fay"
                        },
                        new
                        {
                            Id = 109,
                            Name = "Mrs. Angela Shirley Bednar Jr."
                        },
                        new
                        {
                            Id = 110,
                            Name = "Mrs. Liliana Heaney"
                        },
                        new
                        {
                            Id = 111,
                            Name = "Norwood Towne"
                        },
                        new
                        {
                            Id = 112,
                            Name = "Kaitlyn Kreiger"
                        },
                        new
                        {
                            Id = 113,
                            Name = "Mr. Albert Virgil Collins"
                        },
                        new
                        {
                            Id = 114,
                            Name = "Mozell Keeling"
                        },
                        new
                        {
                            Id = 115,
                            Name = "Willie Berneice Morar Jr."
                        },
                        new
                        {
                            Id = 116,
                            Name = "Bernard Tillman"
                        },
                        new
                        {
                            Id = 117,
                            Name = "Rubie Grady V"
                        },
                        new
                        {
                            Id = 118,
                            Name = "Donavon Vandervort"
                        },
                        new
                        {
                            Id = 119,
                            Name = "Noe Toy"
                        },
                        new
                        {
                            Id = 120,
                            Name = "Ms. Nia Sharon Macejkovic Jr."
                        },
                        new
                        {
                            Id = 121,
                            Name = "Dr. Woodrow VonRueden"
                        },
                        new
                        {
                            Id = 122,
                            Name = "Melvin Witting"
                        },
                        new
                        {
                            Id = 123,
                            Name = "Kailee Graham"
                        },
                        new
                        {
                            Id = 124,
                            Name = "Kira O'Kon V"
                        },
                        new
                        {
                            Id = 125,
                            Name = "Miss Roma Jaiden Rosenbaum"
                        },
                        new
                        {
                            Id = 126,
                            Name = "Elvis Karina Streich IV"
                        },
                        new
                        {
                            Id = 127,
                            Name = "Mortimer Mosciski"
                        },
                        new
                        {
                            Id = 128,
                            Name = "Isabelle Sedrick Franecki MD"
                        },
                        new
                        {
                            Id = 129,
                            Name = "Krista Murphy"
                        },
                        new
                        {
                            Id = 130,
                            Name = "Declan Stanton"
                        },
                        new
                        {
                            Id = 131,
                            Name = "Daren Huels"
                        },
                        new
                        {
                            Id = 132,
                            Name = "Torey Wunsch"
                        },
                        new
                        {
                            Id = 133,
                            Name = "Thea Gislason"
                        },
                        new
                        {
                            Id = 134,
                            Name = "Ms. Joseph Parisian I"
                        },
                        new
                        {
                            Id = 135,
                            Name = "Larissa Randall Murazik IV"
                        },
                        new
                        {
                            Id = 136,
                            Name = "Prof. Noah Reginald Larson"
                        },
                        new
                        {
                            Id = 137,
                            Name = "Ernest Rolfson"
                        },
                        new
                        {
                            Id = 138,
                            Name = "Reagan Greenholt"
                        },
                        new
                        {
                            Id = 139,
                            Name = "Victor Jermain Reichert MD"
                        },
                        new
                        {
                            Id = 140,
                            Name = "Daron Schmeler"
                        },
                        new
                        {
                            Id = 141,
                            Name = "Jalon Bartoletti"
                        },
                        new
                        {
                            Id = 142,
                            Name = "Christine Beahan"
                        },
                        new
                        {
                            Id = 143,
                            Name = "Princess Heathcote"
                        },
                        new
                        {
                            Id = 144,
                            Name = "Miss Pinkie Nienow"
                        },
                        new
                        {
                            Id = 145,
                            Name = "Dr. Ayden Lindsey O'Connell PhD"
                        },
                        new
                        {
                            Id = 146,
                            Name = "Kara Beer"
                        },
                        new
                        {
                            Id = 147,
                            Name = "Lewis Sanford"
                        },
                        new
                        {
                            Id = 148,
                            Name = "Miguel Ullrich"
                        },
                        new
                        {
                            Id = 149,
                            Name = "Alayna Goodwin"
                        },
                        new
                        {
                            Id = 150,
                            Name = "Ansel Abshire"
                        },
                        new
                        {
                            Id = 151,
                            Name = "Mr. Lacy Bud Stehr DVM"
                        },
                        new
                        {
                            Id = 152,
                            Name = "Dulce Doyle"
                        },
                        new
                        {
                            Id = 153,
                            Name = "Benny Ethan Wolff I"
                        },
                        new
                        {
                            Id = 154,
                            Name = "Letha Romaguera V"
                        });
                });

            modelBuilder.Entity("BookStore.Data.Models.Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Store");
                });

            modelBuilder.Entity("BookStore.Data.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("AuthorBook", b =>
                {
                    b.HasOne("BookStore.Data.Models.Author", null)
                        .WithMany()
                        .HasForeignKey("AuthorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookStore.Data.Models.Book", null)
                        .WithMany()
                        .HasForeignKey("BooksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookStore.Data.Models.Book", b =>
                {
                    b.HasOne("BookStore.Data.Models.Store", null)
                        .WithMany("Books")
                        .HasForeignKey("StoreId");
                });

            modelBuilder.Entity("BookStore.Data.Models.Store", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
